
# This file controls Supabase Function settings
project_id = "imrmboyczebjlbnkgjns"

[functions.twilio-token]
verify_jwt = false

[functions.twilio-voice]
verify_jwt = false

[functions.twilio-stream]
verify_jwt = false
