
# A string used to distinguish different Supabase projects on the same host. Defaults to the working
# directory name when running `supabase init`.
project_id = "imrmboyczebjlbnkgjns"

[api]
# Port to use for the API URL.
port = 54321
# Schemas to expose in your API. Tables, views and stored procedures in this schema will get API
# endpoints. public and storage are always included.
schemas = ["public", "storage", "graphql_public"]
# Extra schemas to add to the search_path of every request. public is always included.
extra_search_path = ["public", "extensions"]
# The maximum number of rows returns from a view, table, or stored procedure. Limits payload size
# for accidental or malicious requests.
max_rows = 1000

[db]
# Port to use for the local database URL.
port = 54322
# The database major version to use. This has to be the same as your remote database's. Run `SHOW
# server_version;` on the remote database to check.
major_version = 15

[studio]
# Port to use for Supabase Studio.
port = 54323

# Email testing server. Emails sent with the local dev setup are not actually sent - rather, they
# are monitored, and you can view the emails that would have been sent from the web interface.
[inbucket]
# Port to use for the email testing server web interface.
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
# The maximum file size allowed (e.g. "5MB", "500KB").
file_size_limit = "50MiB"

[auth]
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://localhost:3000"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://localhost:3000"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604,800 seconds (one
# week).
jwt_expiry = 3600
# Allow/disallow new user signups to your project.
enable_signup = true
# If disabled, the refresh token will never expire.
enable_refresh_token_rotation = true
# Allows CAPTCHAs to be embedded in the auth widgets.
enable_captcha_protection = false

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email
# addresses. If disabled, only the new email is required to confirm.
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = false

# Use an external OAuth provider. The full list of providers are: `apple`, `azure`, `bitbucket`,
# `discord`, `facebook`, `github`, `gitlab`, `google`, `keycloak`, `linkedin`, `notion`, `twitch`,
# `twitter`, `slack`, `spotify`, `workos`, `zoom`.
[auth.external.apple]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure,
# or any other third-party OIDC providers.
url = ""

[analytics]
enabled = false
port = 54327
vector_port = 54328
# Setup BigQuery project to enable log viewer on local development stack.
gcp_project_id = ""
gcp_project_number = ""
gcp_jwt_path = "supabase/gcloud.json"

[functions]
[functions.lead-connected]
verify_jwt = true

[functions.analyze-csv-data]
verify_jwt = true

[functions.ai-sms-agent]
verify_jwt = false

[functions.call-disposition]
verify_jwt = true

[functions.analytics]
verify_jwt = true

[functions.analyze-document-type]
verify_jwt = true

[functions.asset-verification]
verify_jwt = true

[functions.dialer-webhook]
verify_jwt = false

[functions.predictive-dialer-webhook]
verify_jwt = false

[functions.predictive-dialer-machine-detection]
verify_jwt = false

[functions.dialer-agent-connect]
verify_jwt = false

[functions.dialer-machine-detection]
verify_jwt = false

[functions.sms-webhook-receiver]
verify_jwt = false

[functions.twilio-token]
verify_jwt = false

[functions.twilio-voice]
verify_jwt = false

[functions.dialer-start]
verify_jwt = true

[functions.start-dialing-session]
verify_jwt = true

[functions.stop-predictive-dialer]
verify_jwt = true

[functions.conditions-update-sms]
verify_jwt = true

[functions.hangup-call]
verify_jwt = true

[functions.loan-approved-sms]
verify_jwt = true

[functions.sms-get-balance]
verify_jwt = true

[functions.sms-send-multiple]
verify_jwt = true

[functions.update-lead]
verify_jwt = true

[functions.proxy-api-call]
verify_jwt = true

[functions.get-calling-list-leads]
verify_jwt = true

[functions.google-auth]
verify_jwt = false

[functions.get-google-auth-url]
verify_jwt = true

[functions.create-pitch-deck]
verify_jwt = true

[functions.save-pitch-deck]
verify_jwt = true

[functions.generate-client-portal]
verify_jwt = true

[functions.twilio-stream]
verify_jwt = false
