
# Project config
project_id = "imrmboyczebjlbnkgjns"

# Auth Server
[auth]
enabled = true

[auth.user_management]
enabled = true

[functions]
node_version = 18

# Make only the twilio functions public, the rest should use JWT verification
[functions.twilio-token]
verify_jwt = false

[functions.twilio-voice]
verify_jwt = false
