
# This file manages Edge Function configuration. We're updating it to make
# store-leads function public (not requiring JWT verification)

[functions]
[functions.store-leads]
verify_jwt = false

[functions.twilio-token] 
verify_jwt = false

[functions.twilio-voice]
verify_jwt = false
