
project_id = "imrmboyczebjlbnkgjns"
[functions.dialer-webhook]
verify_jwt = false
[functions.get-call-updates]
verify_jwt = false
[functions.twilio-token]
verify_jwt = false
[functions.twilio-voice]
verify_jwt = false
[functions.ai-sms-agent]
verify_jwt = false
[functions.sms-webhook-receiver]
verify_jwt = false
