
[functions]
[functions.update-user-account-info]
verify_jwt = true

[functions.loan-onboarding-completed]
verify_jwt = false

[functions.twilio-voice]
verify_jwt = false

[functions.twilio-token]
verify_jwt = false
