
project_id = "imrmboyczebjlbnkgjns"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[storage]
enabled = true

[auth]
enabled = true

[realtime]
enabled = true

[analytics]
enabled = true

[vector]
enabled = true

[functions.twilio-token]
verify_jwt = false

[functions.twilio-voice]
verify_jwt = false

[functions.store-document]
verify_jwt = false

[functions.retrieve-documents]
verify_jwt = false
