
# This file controls the configuration for your Supabase project.
# For the full reference, see:
# https://supabase.com/docs/guides/self-hosting/configuration

project_id = "imrmboyczebjlbnkgjns"

[auth]
site_url = "app.lovable.dev"
additional_redirect_urls = ["*", "https://lovable.dev", "https://app.lovable.dev", "http://localhost:3000", "https://app.lovable.dev/*", "https://app.lovable.dev/#/*"]

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions]
[functions.twilio-token]
verify_jwt = false
[functions.twilio-voice]
verify_jwt = false
[functions.dialer-webhook]
verify_jwt = false
[functions.predictive-dialer-webhook]
verify_jwt = false
[functions.dialer-machine-detection]
verify_jwt = false
