
# project_id is required
project_id = "imrmboyczebjlbnkgjns"

# This is a base template for Supabase Edge Functions
[build]
builder = "supabase/functions-js"
command = ""

[deploy]
provider = "supabase"

[functions.analyze-csv-data]
verify_jwt = true

[functions.retrieve-documents]
verify_jwt = false

[functions.store-document]
verify_jwt = false

[functions.twilio-token]
verify_jwt = false

[functions.twilio-voice]
verify_jwt = false

[functions.get-lead-for-document-manager]
verify_jwt = false
