
# Project config
project_id = "imrmboyczebjlbnkgjns"

# Auth Server
[auth]
enabled = true

[auth.user_management]
enabled = true

[functions]
node_version = 18

# Make these functions public so they don't require authentication
[functions.twilio-token]
verify_jwt = false

[functions.twilio-voice]
verify_jwt = false

[functions.lead-connected]
verify_jwt = false

[functions.get-calling-lists]
verify_jwt = false

[functions.get-calling-list]
verify_jwt = false

[functions.get-calling-list-leads]
verify_jwt = false

# Enable realtime
[realtime]
enabled = true

[realtime.leads]
enabled = true

[realtime.lead_activities]
enabled = true

[realtime.dialing_session_leads]
enabled = true

